version: '3.8'

networks:
  parser-network:
    driver: bridge

services:
  app:
    build:
      context: ./docker/php8.1-fpm
      dockerfile: Dockerfile
    image: parser/php
    container_name: "parser_php"
    restart: always
    volumes:
      - ./project/parser:/var/www/parser.dev
      - ./docker/php8.1-fpm/logs:/var/log/php8.1-fpm
    networks:
      - parser-network

  nginx:
    container_name: "parser_nginx"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./project/parser:/var/www/parser.dev
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - parser-network