version: '3.8'

networks:
  parser:
    driver: bridge

services:
  fpm:
    container_name: "parser_fpm"
    restart: always
    tty: true
    build:
      context: ./docker/php
      args:
        UID: ${CURRENT_UID}
        GID: ${CURRENT_UID}
    user: "root"
    volumes:
      - ./:/app
      - ./docker/dev/php/logs:/var/log/php

  nginx:
    container_name: "parser_nginx"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/logs:/var/log/nginx:cached
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PUBLIC_PORT:-80}:80"
    depends_on:
      - fpm
    links:
      - fpm